config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  namespace :admin do
    root to: 'dashboards#index'
    resources :users
  end

  namespace :general do
    root to: 'generals#index'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/identity.rb
# == Schema Information
#
# Table name: identities
#
#  id              :bigint           not null, primary key
#  email           :string(256)
#  name            :string(50)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_identities_on_email  (email) UNIQUE
#
class Identity < ApplicationRecord
  has_secure_password

  has_one :reservation_admin_role, dependent: :destroy
  has_one :reservation_general_role, dependent: :destroy

  has_many :reservations, dependent: :destroy
  has_many :resources, through: :reservations

  validates :email, uniqueness: true
end

app/models/reservation.rb
# == Schema Information
#
# Table name: reservations
#
#  id          :bigint           not null, primary key
#  end_time    :datetime
#  start_time  :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  identity_id :bigint           not null
#  resource_id :bigint           not null
#
# Indexes
#
#  index_reservations_on_identity_id  (identity_id)
#  index_reservations_on_resource_id  (resource_id)
#
# Foreign Keys
#
#  fk_rails_...  (identity_id => identities.id)
#  fk_rails_...  (resource_id => resources.id)
#
class Reservation < ApplicationRecord
  belongs_to :identity
  belongs_to :resource
end

app/models/reservation_admin_role.rb
# == Schema Information
#
# Table name: reservation_admin_roles
#
#  id          :bigint           not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  identity_id :bigint           not null
#
# Indexes
#
#  index_reservation_admin_roles_on_identity_id  (identity_id)
#
# Foreign Keys
#
#  fk_rails_...  (identity_id => identities.id)
#
class ReservationAdminRole < ApplicationRecord
  belongs_to :identity
end

app/models/reservation_general_role.rb
# == Schema Information
#
# Table name: reservation_general_roles
#
#  id          :bigint           not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  identity_id :bigint           not null
#
# Indexes
#
#  index_reservation_general_roles_on_identity_id  (identity_id)
#
# Foreign Keys
#
#  fk_rails_...  (identity_id => identities.id)
#
class ReservationGeneralRole < ApplicationRecord
  belongs_to :identity
end

app/models/resource.rb
# == Schema Information
#
# Table name: resources
#
#  id         :bigint           not null, primary key
#  name       :string(50)
#  note       :string(1024)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Resource < ApplicationRecord
  has_many :reservations
  has_many :identities, through: :reservations
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ApplicationController
    layout 'admin'
    before_action :authenticate_admin

    private

    def authenticate_admin
      if session[:reservation_admin]
        @current_user = Identity.find(session[:reservation_admin])
      else
        redirect_to login_path, alert: '管理者アカウントでログインしてください。'
      end
    end
  end
end

app/controllers/admin/dashboards_controller.rb
module Admin
  class DashboardsController < Admin::ApplicationController
    def index
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    before_action :set_user, only: %i[show]

    def index
      @identities =
        Identity.includes(:reservation_admin_role, :reservation_general_role)
                .where.not(reservation_admin_role: { id: nil })
                .or(Identity.where.not(reservation_general_role: { id: nil }))
                .order(:created_at)
    end

    def show
    end

    private

    def set_user
      @user = Identity.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    identity = authenticate_user(params[:email], params[:password])

    if identity
      assign_session_and_redirect(identity)
    else
      redirect_to login_path, alert: 'メールアドレスまたはパスワードが無効です。'
    end
  end

  def destroy
    session.delete(:reservation_admin)
    session.delete(:reservation_general)
    # OPTIMIZED: turboの影響でFlashが正しく表示できていないので、修正する
    redirect_to login_path, notice: 'ログアウトしました。'
  end

  private

  def authenticate_user(email, password)
    identity = Identity.find_by(email:)
    return identity if identity&.authenticate(password)
  end

  def assign_session_and_redirect(identity)
    if identity.reservation_admin_role
      session[:reservation_admin] = identity.id
      redirect_to admin_root_path
    elsif identity.reservation_general_role
      session[:reservation_general] = identity.id
      redirect_to general_root_path
    else
      redirect_to login_path, alert: 'このIDにはロールが割り当てられていません。'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/users/index.html.erb
<div class="users-management">
  <h1>ユーザー管理</h1>

  <table>
    <thead>
      <tr>
        <%# human_attributes %>
        <th><%= Identity.human_attribute_name(:name) %></th>
        <th><%= Identity.human_attribute_name(:email) %></th>
        <th><%= Identity.human_attribute_name(:reservation_admin_role) %></th>
        <th><%= Identity.human_attribute_name(:reservation_general_role) %></th>
        <th><%= Identity.human_attribute_name(:created_at) %></th>
        <th><%= Identity.human_attribute_name(:updated_at) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @identities.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.reservation_admin_role ? '●' : '' %></td>
          <td><%= user.reservation_general_role ? '●' : '' %></td>
          <td><%= l(user.created_at, format: :date_only) %></td>
          <td><%= l(user.updated_at, format: :date_only) %></td>
          <td><%= link_to '詳細', admin_user_path(user), class: 'button gray-button' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/_side_menu.html.erb
<nav class="side-menu">
  <div class="menu-header">
    <h1>
      <%= link_to 'Admin Panel', admin_root_path %>
    </h1>
  </div>
  <ul>
    <li><%= link_to 'Resources', admin_root_path %></li>
    <li><%= link_to 'Users', admin_users_path %></li>
    <li><%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete } %></li>
  </ul>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Panel</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'admin/application', media: 'all' %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <%= render 'layouts/side_menu' %>
  <div class="content">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="flash-<%= message_type %>">
        <%= image_tag "#{message_type}.svg", alt: "#{message_type} icon", class: "flash-icon" %>
        <span><%= message %></span>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>